export interface UserCfopItem {
  cfop: string;
  descricao: string;
  classe: string;
  tipoOperacao: 'Onerosas' | 'Não Onerosas' | 'Depende - Avaliar cada Cenário SGB';
}

export const USER_CFOP_LIST: UserCfopItem[] = [
  // ── SÉRIE 1000: ENTRADAS ESTADUAIS ──
  { cfop: '1101', descricao: 'Compra para industrialização ou produção rural', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '1102', descricao: 'Compra para comercialização', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '1111', descricao: 'Compra para industrialização de mercadoria recebida anteriormente em consignação industrial', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '1113', descricao: 'Compra para comercialização, de mercadoria recebida anteriormente em consignação mercantil', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '1116', descricao: 'Compra para industrialização ou produção rural originada de encomenda para recebimento futuro', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '1117', descricao: 'Compra para comercialização originada de encomenda para recebimento futuro', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '1118', descricao: 'Compra de mercadoria para comercialização pelo adquirente originário, entregue pelo vendedor remetente ao destinatário, em venda à ordem', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '1120', descricao: 'Compra para industrialização, em venda à ordem, já recebida do vendedor remetente', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '1121', descricao: 'Compra para comercialização, em venda à ordem, já recebida do vendedor remetente', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '1122', descricao: 'Compra para industrialização em que a mercadoria foi remetida pelo fornecedor ao industrializador sem transitar pelo estabelecimento adquirente', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '1124', descricao: 'Industrialização efetuada por outra empresa', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '1125', descricao: 'Industrialização efetuada por outra empresa quando a mercadoria remetida para utilização no processo de industrialização não transitou pelo estabelecimento adquirente da mercadoria', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '1126', descricao: 'Compra para utilização na prestação de serviço sujeito ao ICMS', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '1128', descricao: 'Compra para utilização na prestação de serviço sujeito ao ISS', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '1151', descricao: 'Transferência para industrialização ou produção rural', classe: 'Transferência', tipoOperacao: 'Não Onerosas' },
  { cfop: '1152', descricao: 'Transferência para comercialização', classe: 'Transferência', tipoOperacao: 'Não Onerosas' },
  { cfop: '1153', descricao: 'Transferência de energia elétrica para distribuição', classe: 'Transferência', tipoOperacao: 'Não Onerosas' },
  { cfop: '1154', descricao: 'Transferência para utilização na prestação de serviço', classe: 'Transferência', tipoOperacao: 'Não Onerosas' },
  { cfop: '1201', descricao: 'Devolução de venda de produção do estabelecimento', classe: 'Dev. venda', tipoOperacao: 'Onerosas' },
  { cfop: '1202', descricao: 'Devolução de venda de mercadoria adquirida ou recebida de terceiros', classe: 'Dev. venda', tipoOperacao: 'Onerosas' },
  { cfop: '1203', descricao: 'Devolução de venda de produção do estabelecimento, destinada à Zona Franca de Manaus ou áreas de livre comércio', classe: 'Dev. venda', tipoOperacao: 'Onerosas' },
  { cfop: '1204', descricao: 'Devolução de venda de mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou áreas de livre comércio', classe: 'Dev. venda', tipoOperacao: 'Onerosas' },
  { cfop: '1205', descricao: 'Anulação de valor relativo à prestação de serviço de comunicação', classe: 'Anulação', tipoOperacao: 'Onerosas' },
  { cfop: '1206', descricao: 'Anulação de valor relativo à prestação de serviço de transporte', classe: 'Anulação', tipoOperacao: 'Onerosas' },
  { cfop: '1207', descricao: 'Anulação de valor relativo à venda de energia elétrica', classe: 'Anulação', tipoOperacao: 'Onerosas' },
  { cfop: '1208', descricao: 'Devolução de produção do estabelecimento, remetida em transferência', classe: 'Transferência', tipoOperacao: 'Não Onerosas' },
  { cfop: '1209', descricao: 'Devolução de mercadoria adquirida ou recebida de terceiros, remetida em transferência', classe: 'Transferência', tipoOperacao: 'Não Onerosas' },
  { cfop: '1251', descricao: 'Compra de energia elétrica para distribuição ou comercialização', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '1252', descricao: 'Compra de energia elétrica por estabelecimento industrial', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '1253', descricao: 'Compra de energia elétrica por estabelecimento comercial', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '1254', descricao: 'Compra de energia elétrica por estabelecimento prestador de serviço de transporte', classe: 'Entrada', tipoOperacao: 'Onerosas' },
  { cfop: '1255', descricao: 'Compra de energia elétrica por estabelecimento prestador de serviço de comunicação', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '1256', descricao: 'Compra de energia elétrica por estabelecimento de produtor rural', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '1257', descricao: 'Compra de energia elétrica para consumo por demanda contratada', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '1301', descricao: 'Aquisição de serviço de comunicação para execução de serviço da mesma natureza', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '1302', descricao: 'Aquisição de serviço de comunicação por estabelecimento industrial', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '1303', descricao: 'Aquisição de serviço de comunicação por estabelecimento comercial', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '1304', descricao: 'Aquisição de serviço de comunicação por estabelecimento de prestador de serviço de transporte', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '1305', descricao: 'Aquisição de serviço de comunicação por estabelecimento de geradora ou de distribuidora de energia elétrica', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '1306', descricao: 'Aquisição de serviço de comunicação por estabelecimento de produtor rural', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '1351', descricao: 'Aquisição de serviço de transporte para execução de serviço da mesma natureza', classe: 'Aquisição de Transporte', tipoOperacao: 'Onerosas' },
  { cfop: '1352', descricao: 'Aquisição de serviço de transporte por estabelecimento industrial', classe: 'Aquisição de Transporte', tipoOperacao: 'Onerosas' },
  { cfop: '1353', descricao: 'Aquisição de serviço de transporte por estabelecimento comercial', classe: 'Aquisição de Transporte', tipoOperacao: 'Onerosas' },
  { cfop: '1354', descricao: 'Aquisição de serviço de transporte por estabelecimento de prestador de serviço de comunicação', classe: 'Aquisição de Transporte', tipoOperacao: 'Onerosas' },
  { cfop: '1355', descricao: 'Aquisição de serviço de transporte por estabelecimento de geradora ou de distribuidora de energia elétrica', classe: 'Aquisição de Transporte', tipoOperacao: 'Onerosas' },
  { cfop: '1356', descricao: 'Aquisição de serviço de transporte por estabelecimento de produtor rural', classe: 'Aquisição de Transporte', tipoOperacao: 'Onerosas' },
  { cfop: '1360', descricao: 'Aquisição de serviço de transporte por contribuinte substituto em relação ao serviço de transporte', classe: 'Aquisição de Transporte', tipoOperacao: 'Onerosas' },
  { cfop: '1401', descricao: 'Compra para industrialização ou produção rural em operação com mercadoria sujeita ao regime de substituição tributária', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '1403', descricao: 'Compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '1406', descricao: 'Compra de bem para o ativo imobilizado cuja mercadoria está sujeita ao regime de substituição tributária', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '1407', descricao: 'Compra de mercadoria para uso ou consumo cuja mercadoria está sujeita ao regime de substituição tributária', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '1408', descricao: 'Transferência para industrialização ou produção rural em operação com mercadoria sujeita ao regime de substituição tributária', classe: 'Transferência', tipoOperacao: 'Não Onerosas' },
  { cfop: '1409', descricao: 'Transferência para comercialização em operação com mercadoria sujeita ao regime de substituição tributária', classe: 'Transferência', tipoOperacao: 'Não Onerosas' },
  { cfop: '1410', descricao: 'Devolução de venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária', classe: 'Dev. venda', tipoOperacao: 'Onerosas' },
  { cfop: '1411', descricao: 'Devolução de venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária', classe: 'Dev. venda', tipoOperacao: 'Onerosas' },
  { cfop: '1414', descricao: 'Retorno de produção do estabelecimento, remetida para venda fora do estabelecimento em operação com produto sujeito ao regime de substituição tributária', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '1415', descricao: 'Retorno de mercadoria adquirida ou recebida de terceiros, remetida para venda fora do estabelecimento em operação com mercadoria sujeita ao regime de substituição tributária', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '1451', descricao: 'Retorno de animal do estabelecimento produtor', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '1452', descricao: 'Retorno de insumo não utilizado na produção', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '1501', descricao: 'Entrada de mercadoria recebida com fim específico de exportação', classe: 'Entrada', tipoOperacao: 'Não Onerosas' },
  { cfop: '1503', descricao: 'Entrada decorrente de devolução de produto remetido com fim específico de exportação, de produção do estabelecimento', classe: 'Dev. remessa', tipoOperacao: 'Não Onerosas' },
  { cfop: '1504', descricao: 'Entrada decorrente de devolução de mercadoria remetida com fim específico de exportação, adquirida ou recebida de terceiros', classe: 'Dev. remessa', tipoOperacao: 'Não Onerosas' },
  { cfop: '1505', descricao: 'Entrada decorrente de devolução simbólica de mercadorias remetidas para formação de lote de exportação, de produtos industrializados ou produzidos pelo próprio estabelecimento.', classe: 'Dev. remessa', tipoOperacao: 'Não Onerosas' },
  { cfop: '1506', descricao: 'Entrada decorrente de devolução simbólica de mercadorias, adquiridas ou recebidas de terceiros, remetidas para formação de lote de exportação.', classe: 'Dev. remessa', tipoOperacao: 'Não Onerosas' },
  { cfop: '1551', descricao: 'Compra de bem para o ativo imobilizado', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '1552', descricao: 'Transferência de bem do ativo imobilizado', classe: 'Transferência', tipoOperacao: 'Não Onerosas' },
  { cfop: '1553', descricao: 'Devolução de venda de bem do ativo imobilizado', classe: 'Dev. venda', tipoOperacao: 'Onerosas' },
  { cfop: '1554', descricao: 'Retorno de bem do ativo imobilizado remetido para uso fora do estabelecimento', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '1555', descricao: 'Entrada de bem do ativo imobilizado de terceiro, remetido para uso no estabelecimento', classe: 'Entrada', tipoOperacao: 'Não Onerosas' },
  { cfop: '1556', descricao: 'Compra de material para uso ou consumo', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '1557', descricao: 'Transferência de material para uso ou consumo', classe: 'Transferência', tipoOperacao: 'Não Onerosas' },
  { cfop: '1601', descricao: 'Recebimento, por transferência, de crédito de ICMS', classe: 'Financeira', tipoOperacao: 'Não Onerosas' },
  { cfop: '1602', descricao: 'Recebimento, por transferência, de saldo credor de ICMS de outro estabelecimento da mesma empresa, para compensação de saldo devedor de ICMS', classe: 'Financeira', tipoOperacao: 'Não Onerosas' },
  { cfop: '1603', descricao: 'Ressarcimento de ICMS retido por substituição tributária', classe: 'Ressarcimento', tipoOperacao: 'Não Onerosas' },
  { cfop: '1604', descricao: 'Lançamento do crédito relativo à compra de bem para o ativo imobilizado', classe: 'Financeira', tipoOperacao: 'Não Onerosas' },
  { cfop: '1605', descricao: 'Recebimento, por transferência, de saldo devedor de ICMS de outro estabelecimento da mesma empresa.', classe: 'Financeira', tipoOperacao: 'Não Onerosas' },
  { cfop: '1651', descricao: 'Compra de combustível ou lubrificante para industrialização subseqüente', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '1652', descricao: 'Compra de combustível ou lubrificante para comercialização', classe: 'Compra de Combustível', tipoOperacao: 'Onerosas' },
  { cfop: '1653', descricao: 'Compra de combustível ou lubrificante por consumidor ou usuário final', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '1657', descricao: 'Retorno de remessa de combustíveis ou lubrificantes para venda fora do estabelecimento', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '1658', descricao: 'Transferência de combustível e lubrificante para industrialização', classe: 'Transferência', tipoOperacao: 'Não Onerosas' },
  { cfop: '1659', descricao: 'Transferência de combustível e lubrificante para comercialização', classe: 'Transferência Combustível', tipoOperacao: 'Não Onerosas' },
  { cfop: '1660', descricao: 'Devolução de venda de combustível ou lubrificante destinado à industrialização subseqüente', classe: 'Dev. venda', tipoOperacao: 'Onerosas' },
  { cfop: '1661', descricao: 'Devolução de venda de combustível ou lubrificante destinado à comercialização', classe: 'Dev. Venda de Combustível', tipoOperacao: 'Onerosas' },
  { cfop: '1662', descricao: 'Devolução de venda de combustível ou lubrificante destinado a consumidor ou usuário final', classe: 'Dev. Venda de Combustível', tipoOperacao: 'Onerosas' },
  { cfop: '1663', descricao: 'Entrada de combustível ou lubrificante para armazenagem', classe: 'Entrada', tipoOperacao: 'Não Onerosas' },
  { cfop: '1664', descricao: 'Retorno de combustível ou lubrificante remetido para armazenagem', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '1901', descricao: 'Entrada para industrialização por encomenda', classe: 'Entrada', tipoOperacao: 'Não Onerosas' },
  { cfop: '1902', descricao: 'Retorno de mercadoria remetida para industrialização por encomenda', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '1903', descricao: 'Entrada de mercadoria remetida para industrialização e não aplicada no referido processo', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '1904', descricao: 'Retorno de remessa para venda fora do estabelecimento', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '1905', descricao: 'Entrada de mercadoria recebida para depósito em depósito fechado ou armazém geral', classe: 'Entrada', tipoOperacao: 'Não Onerosas' },
  { cfop: '1906', descricao: 'Retorno de mercadoria remetida para depósito fechado ou armazém geral', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '1907', descricao: 'Retorno simbólico de mercadoria remetida para depósito fechado ou armazém geral', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '1908', descricao: 'Entrada de bem por conta de contrato de comodato', classe: 'Entrada', tipoOperacao: 'Não Onerosas' },
  { cfop: '1909', descricao: 'Retorno de bem remetido por conta de contrato de comodato', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '1910', descricao: 'Entrada de bonificação, doação ou brinde', classe: 'Entrada', tipoOperacao: 'Onerosas' },
  { cfop: '1911', descricao: 'Entrada de amostra grátis', classe: 'Entrada', tipoOperacao: 'Não Onerosas' },
  { cfop: '1912', descricao: 'Entrada de mercadoria ou bem recebido para demonstração', classe: 'Entrada', tipoOperacao: 'Não Onerosas' },
  { cfop: '1913', descricao: 'Retorno de mercadoria ou bem remetido para demonstração', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '1914', descricao: 'Retorno de mercadoria ou bem remetido para exposição ou feira', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '1915', descricao: 'Entrada de mercadoria ou bem recebido para conserto ou reparo', classe: 'Entrada', tipoOperacao: 'Não Onerosas' },
  { cfop: '1916', descricao: 'Retorno de mercadoria ou bem remetido para conserto ou reparo', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '1917', descricao: 'Entrada de mercadoria recebida em consignação mercantil ou industrial', classe: 'Entrada', tipoOperacao: 'Não Onerosas' },
  { cfop: '1918', descricao: 'Devolução de mercadoria remetida em consignação mercantil ou industrial', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '1919', descricao: 'Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, remetida anteriormente em consignação mercantil ou industrial', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '1920', descricao: 'Entrada de vasilhame ou sacaria', classe: 'Entrada', tipoOperacao: 'Não Onerosas' },
  { cfop: '1921', descricao: 'Retorno de vasilhame ou sacaria', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '1922', descricao: 'Lançamento efetuado a título de simples faturamento decorrente de compra para recebimento futuro', classe: 'Financeira', tipoOperacao: 'Não Onerosas' },
  { cfop: '1923', descricao: 'Entrada de mercadoria recebida do vendedor remetente, em venda à ordem', classe: 'Entrada', tipoOperacao: 'Não Onerosas' },
  { cfop: '1924', descricao: 'Entrada para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente', classe: 'Entrada', tipoOperacao: 'Não Onerosas' },
  { cfop: '1925', descricao: 'Retorno de mercadoria remetida para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '1926', descricao: 'Lançamento efetuado a título de reclassificação de mercadoria decorrente de formação de kit ou de sua desagregação', classe: 'Aj. estoque', tipoOperacao: 'Não Onerosas' },
  { cfop: '1931', descricao: 'Lançamento efetuado pelo tomador do serviço de transporte quando a responsabilidade de retenção do imposto for atribuída ao remetente ou alienante da mercadoria', classe: 'Financeira', tipoOperacao: 'Não Onerosas' },
  { cfop: '1932', descricao: 'Aquisição de serviço de transporte iniciado em unidade da Federação diversa daquela onde inscrito o prestador.', classe: 'Aquisição de Transporte', tipoOperacao: 'Onerosas' },
  { cfop: '1933', descricao: 'Aquisição de serviço tributado pelo ISS', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '1934', descricao: 'Entrada simbólica de mercadoria recebida para depósito ou armazém geral', classe: 'Entrada', tipoOperacao: 'Não Onerosas' },
  { cfop: '1949', descricao: 'Outra entrada de mercadoria ou prestação de serviço não especificada', classe: 'Out. entr/aquis', tipoOperacao: 'Depende - Avaliar cada Cenário SGB' },

  // ── SÉRIE 2000: ENTRADAS INTERESTADUAIS ──
  { cfop: '2101', descricao: 'Compra para industrialização ou produção rural', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '2102', descricao: 'Compra para comercialização', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '2111', descricao: 'Compra para industrialização de mercadoria recebida anteriormente em consignação industrial', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '2113', descricao: 'Compra para comercialização, de mercadoria recebida anteriormente em consignação mercantil', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '2116', descricao: 'Compra para industrialização ou produção rural originada de encomenda para recebimento futuro', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '2117', descricao: 'Compra para comercialização originada de encomenda para recebimento futuro', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '2118', descricao: 'Compra de mercadoria para comercialização pelo adquirente originário, entregue pelo vendedor remetente ao destinatário, em venda à ordem', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '2120', descricao: 'Compra para industrialização, em venda à ordem, já recebida do vendedor remetente', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '2121', descricao: 'Compra para comercialização, em venda à ordem, já recebida do vendedor remetente', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '2122', descricao: 'Compra para industrialização em que a mercadoria foi remetida pelo fornecedor ao industrializador sem transitar pelo estabelecimento adquirente', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '2124', descricao: 'Industrialização efetuada por outra empresa', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '2125', descricao: 'Industrialização efetuada por outra empresa quando a mercadoria remetida para utilização no processo de industrialização não transitou pelo estabelecimento adquirente da mercadoria', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '2126', descricao: 'Compra para utilização na prestação de serviço sujeito ao ICMS', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '2128', descricao: 'Compra para utilização na prestação de serviço sujeito ao ISS', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '2151', descricao: 'Transferência para industrialização ou produção rural', classe: 'Transferência', tipoOperacao: 'Não Onerosas' },
  { cfop: '2152', descricao: 'Transferência para comercialização', classe: 'Transferência', tipoOperacao: 'Não Onerosas' },
  { cfop: '2153', descricao: 'Transferência de energia elétrica para distribuição', classe: 'Transferência', tipoOperacao: 'Não Onerosas' },
  { cfop: '2154', descricao: 'Transferência para utilização na prestação de serviço', classe: 'Transferência', tipoOperacao: 'Não Onerosas' },
  { cfop: '2201', descricao: 'Devolução de venda de produção do estabelecimento', classe: 'Dev. venda', tipoOperacao: 'Onerosas' },
  { cfop: '2202', descricao: 'Devolução de venda de mercadoria adquirida ou recebida de terceiros', classe: 'Dev. venda', tipoOperacao: 'Onerosas' },
  { cfop: '2203', descricao: 'Devolução de venda de produção do estabelecimento, destinada à Zona Franca de Manaus ou áreas de livre comércio', classe: 'Dev. venda', tipoOperacao: 'Onerosas' },
  { cfop: '2204', descricao: 'Devolução de venda de mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou áreas de livre comércio', classe: 'Dev. venda', tipoOperacao: 'Onerosas' },
  { cfop: '2205', descricao: 'Anulação de valor relativo à prestação de serviço de comunicação', classe: 'Anulação', tipoOperacao: 'Onerosas' },
  { cfop: '2206', descricao: 'Anulação de valor relativo à prestação de serviço de transporte', classe: 'Anulação', tipoOperacao: 'Onerosas' },
  { cfop: '2207', descricao: 'Anulação de valor relativo à venda de energia elétrica', classe: 'Anulação', tipoOperacao: 'Onerosas' },
  { cfop: '2208', descricao: 'Devolução de produção do estabelecimento, remetida em transferência', classe: 'Transferência', tipoOperacao: 'Não Onerosas' },
  { cfop: '2209', descricao: 'Devolução de mercadoria adquirida ou recebida de terceiros, remetida em transferência', classe: 'Transferência', tipoOperacao: 'Não Onerosas' },
  { cfop: '2251', descricao: 'Compra de energia elétrica para distribuição ou comercialização', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '2252', descricao: 'Compra de energia elétrica por estabelecimento industrial', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '2253', descricao: 'Compra de energia elétrica por estabelecimento comercial', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '2254', descricao: 'Compra de energia elétrica por estabelecimento prestador de serviço de transporte', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '2255', descricao: 'Compra de energia elétrica por estabelecimento prestador de serviço de comunicação', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '2256', descricao: 'Compra de energia elétrica por estabelecimento de produtor rural', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '2257', descricao: 'Compra de energia elétrica para consumo por demanda contratada', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '2301', descricao: 'Aquisição de serviço de comunicação para execução de serviço da mesma natureza', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '2302', descricao: 'Aquisição de serviço de comunicação por estabelecimento industrial', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '2303', descricao: 'Aquisição de serviço de comunicação por estabelecimento comercial', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '2304', descricao: 'Aquisição de serviço de comunicação por estabelecimento de prestador de serviço de transporte', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '2305', descricao: 'Aquisição de serviço de comunicação por estabelecimento de geradora ou de distribuidora de energia elétrica', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '2306', descricao: 'Aquisição de serviço de comunicação por estabelecimento de produtor rural', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '2351', descricao: 'Aquisição de serviço de transporte para execução de serviço da mesma natureza', classe: 'Aquisição de Transporte', tipoOperacao: 'Onerosas' },
  { cfop: '2352', descricao: 'Aquisição de serviço de transporte por estabelecimento industrial', classe: 'Aquisição de Transporte', tipoOperacao: 'Onerosas' },
  { cfop: '2353', descricao: 'Aquisição de serviço de transporte por estabelecimento comercial', classe: 'Aquisição de Transporte', tipoOperacao: 'Onerosas' },
  { cfop: '2354', descricao: 'Aquisição de serviço de transporte por estabelecimento de prestador de serviço de comunicação', classe: 'Aquisição de Transporte', tipoOperacao: 'Onerosas' },
  { cfop: '2355', descricao: 'Aquisição de serviço de transporte por estabelecimento de geradora ou de distribuidora de energia elétrica', classe: 'Aquisição de Transporte', tipoOperacao: 'Onerosas' },
  { cfop: '2356', descricao: 'Aquisição de serviço de transporte por estabelecimento de produtor rural', classe: 'Aquisição de Transporte', tipoOperacao: 'Onerosas' },
  { cfop: '2401', descricao: 'Compra para industrialização ou produção rural em operação com mercadoria sujeita ao regime de substituição tributária', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '2403', descricao: 'Compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '2406', descricao: 'Compra de bem para o ativo imobilizado cuja mercadoria está sujeita ao regime de substituição tributária', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '2407', descricao: 'Compra de mercadoria para uso ou consumo cuja mercadoria está sujeita ao regime de substituição tributária', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '2408', descricao: 'Transferência para industrialização ou produção rural em operação com mercadoria sujeita ao regime de substituição tributária', classe: 'Transferência', tipoOperacao: 'Não Onerosas' },
  { cfop: '2409', descricao: 'Transferência para comercialização em operação com mercadoria sujeita ao regime de substituição tributária', classe: 'Transferência', tipoOperacao: 'Não Onerosas' },
  { cfop: '2410', descricao: 'Devolução de venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária', classe: 'Dev. venda', tipoOperacao: 'Onerosas' },
  { cfop: '2411', descricao: 'Devolução de venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária', classe: 'Dev. venda', tipoOperacao: 'Onerosas' },
  { cfop: '2414', descricao: 'Retorno de produção do estabelecimento, remetida para venda fora do estabelecimento em operação com produto sujeito ao regime de substituição tributária', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '2415', descricao: 'Retorno de mercadoria adquirida ou recebida de terceiros, remetida para venda fora do estabelecimento em operação com mercadoria sujeita ao regime de substituição tributária', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '2501', descricao: 'Entrada de mercadoria recebida com fim específico de exportação', classe: 'Entrada', tipoOperacao: 'Não Onerosas' },
  { cfop: '2503', descricao: 'Entrada decorrente de devolução de produto remetido com fim específico de exportação, de produção do estabelecimento', classe: 'Dev. remessa', tipoOperacao: 'Não Onerosas' },
  { cfop: '2504', descricao: 'Entrada decorrente de devolução de mercadoria remetida com fim específico de exportação, adquirida ou recebida de terceiros', classe: 'Dev. remessa', tipoOperacao: 'Não Onerosas' },
  { cfop: '2505', descricao: 'Entrada decorrente de devolução simbólica de mercadorias remetidas para formação de lote de exportação, de produtos industrializados ou produzidos pelo próprio estabelecimento.', classe: 'Dev. remessa', tipoOperacao: 'Não Onerosas' },
  { cfop: '2506', descricao: 'Entrada decorrente de devolução simbólica de mercadorias, adquiridas ou recebidas de terceiros, remetidas para formação de lote de exportação.', classe: 'Dev. remessa', tipoOperacao: 'Não Onerosas' },
  { cfop: '2551', descricao: 'Compra de bem para o ativo imobilizado', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '2552', descricao: 'Transferência de bem do ativo imobilizado', classe: 'Transferência', tipoOperacao: 'Não Onerosas' },
  { cfop: '2553', descricao: 'Devolução de venda de bem do ativo imobilizado', classe: 'Dev. venda', tipoOperacao: 'Onerosas' },
  { cfop: '2554', descricao: 'Retorno de bem do ativo imobilizado remetido para uso fora do estabelecimento', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '2555', descricao: 'Entrada de bem do ativo imobilizado de terceiro, remetido para uso no estabelecimento', classe: 'Entrada', tipoOperacao: 'Não Onerosas' },
  { cfop: '2556', descricao: 'Compra de material para uso ou consumo', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '2557', descricao: 'Transferência de material para uso ou consumo', classe: 'Transferência', tipoOperacao: 'Não Onerosas' },
  { cfop: '2603', descricao: 'Ressarcimento de ICMS retido por substituição tributária', classe: 'Ressarcimento', tipoOperacao: 'Não Onerosas' },
  { cfop: '2651', descricao: 'Compra de combustível ou lubrificante para industrialização subseqüente', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '2652', descricao: 'Compra de combustível ou lubrificante para comercialização', classe: 'Compra de Combustível', tipoOperacao: 'Onerosas' },
  { cfop: '2653', descricao: 'Compra de combustível ou lubrificante por consumidor ou usuário final', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '2657', descricao: 'Retorno de remessa de combustíveis ou lubrificantes para venda fora do estabelecimento', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '2658', descricao: 'Transferência de combustível e lubrificante para industrialização', classe: 'Transferência', tipoOperacao: 'Não Onerosas' },
  { cfop: '2659', descricao: 'Transferência de combustível e lubrificante para comercialização', classe: 'Transferência Combustível', tipoOperacao: 'Não Onerosas' },
  { cfop: '2660', descricao: 'Devolução de venda de combustível ou lubrificante destinado à industrialização subseqüente', classe: 'Dev. venda', tipoOperacao: 'Onerosas' },
  { cfop: '2661', descricao: 'Devolução de venda de combustível ou lubrificante destinado à comercialização', classe: 'Dev. Venda de Combustível', tipoOperacao: 'Onerosas' },
  { cfop: '2662', descricao: 'Devolução de venda de combustível ou lubrificante destinado a consumidor ou usuário final', classe: 'Dev. Venda de Combustível', tipoOperacao: 'Onerosas' },
  { cfop: '2663', descricao: 'Entrada de combustível ou lubrificante para armazenagem', classe: 'Entrada', tipoOperacao: 'Não Onerosas' },
  { cfop: '2664', descricao: 'Retorno de combustível ou lubrificante remetido para armazenagem', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '2901', descricao: 'Entrada para industrialização por encomenda', classe: 'Entrada', tipoOperacao: 'Não Onerosas' },
  { cfop: '2902', descricao: 'Retorno de mercadoria remetida para industrialização por encomenda', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '2903', descricao: 'Entrada de mercadoria remetida para industrialização e não aplicada no referido processo', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '2904', descricao: 'Retorno de remessa para venda fora do estabelecimento', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '2905', descricao: 'Entrada de mercadoria recebida para depósito em depósito fechado ou armazém geral', classe: 'Entrada', tipoOperacao: 'Não Onerosas' },
  { cfop: '2906', descricao: 'Retorno de mercadoria remetida para depósito fechado ou armazém geral', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '2907', descricao: 'Retorno simbólico de mercadoria remetida para depósito fechado ou armazém geral', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '2908', descricao: 'Entrada de bem por conta de contrato de comodato', classe: 'Entrada', tipoOperacao: 'Não Onerosas' },
  { cfop: '2909', descricao: 'Retorno de bem remetido por conta de contrato de comodato', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '2910', descricao: 'Entrada de bonificação, doação ou brinde', classe: 'Entrada', tipoOperacao: 'Onerosas' },
  { cfop: '2911', descricao: 'Entrada de amostra grátis', classe: 'Entrada', tipoOperacao: 'Não Onerosas' },
  { cfop: '2912', descricao: 'Entrada de mercadoria ou bem recebido para demonstração', classe: 'Entrada', tipoOperacao: 'Não Onerosas' },
  { cfop: '2913', descricao: 'Retorno de mercadoria ou bem remetido para demonstração', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '2914', descricao: 'Retorno de mercadoria ou bem remetido para exposição ou feira', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '2915', descricao: 'Entrada de mercadoria ou bem recebido para conserto ou reparo', classe: 'Entrada', tipoOperacao: 'Não Onerosas' },
  { cfop: '2916', descricao: 'Retorno de mercadoria ou bem remetido para conserto ou reparo', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '2917', descricao: 'Entrada de mercadoria recebida em consignação mercantil ou industrial', classe: 'Entrada', tipoOperacao: 'Não Onerosas' },
  { cfop: '2918', descricao: 'Devolução de mercadoria remetida em consignação mercantil ou industrial', classe: 'Dev. remessa', tipoOperacao: 'Não Onerosas' },
  { cfop: '2919', descricao: 'Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, recebida anteriormente em consignação mercantil ou industrial', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '2920', descricao: 'Entrada de vasilhame ou sacaria', classe: 'Entrada', tipoOperacao: 'Não Onerosas' },
  { cfop: '2921', descricao: 'Retorno de vasilhame ou sacaria', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '2922', descricao: 'Lançamento efetuado a título de simples faturamento decorrente de compra para recebimento futuro', classe: 'Financeira', tipoOperacao: 'Não Onerosas' },
  { cfop: '2923', descricao: 'Entrada de mercadoria recebida do vendedor remetente, em venda à ordem', classe: 'Entrada', tipoOperacao: 'Não Onerosas' },
  { cfop: '2924', descricao: 'Entrada para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente', classe: 'Entrada', tipoOperacao: 'Não Onerosas' },
  { cfop: '2925', descricao: 'Retorno de mercadoria remetida para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '2931', descricao: 'Lançamento efetuado pelo tomador do serviço de transporte quando a responsabilidade de retenção do imposto for atribuída ao remetente ou alienante da mercadoria', classe: 'Financeira', tipoOperacao: 'Não Onerosas' },
  { cfop: '2932', descricao: 'Aquisição de serviço de transporte iniciado em unidade da Federação diversa daquela onde inscrito o prestador.', classe: 'Aquisição de Transporte', tipoOperacao: 'Onerosas' },
  { cfop: '2933', descricao: 'Aquisição de serviço tributado pelo ISS', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '2934', descricao: 'Entrada simbólica de mercadoria recebida para depósito ou armazém geral', classe: 'Entrada', tipoOperacao: 'Não Onerosas' },
  { cfop: '2949', descricao: 'Outra entrada de mercadoria ou prestação de serviço não especificado', classe: 'Out. entr/aquis', tipoOperacao: 'Depende - Avaliar cada Cenário SGB' },

  // ── SÉRIE 3000: IMPORTAÇÕES (EXTERIOR) ──
  { cfop: '3101', descricao: 'Compra para industrialização ou produção rural', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '3102', descricao: 'Compra para comercialização', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '3126', descricao: 'Compra para utilização na prestação de serviço sujeito ao ICMS', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '3127', descricao: 'Compra para industrialização sob o regime de drawback', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '3128', descricao: 'Compra para utilização na prestação de serviço sujeito ao ISS', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '3201', descricao: 'Devolução de venda de produção do estabelecimento', classe: 'Dev. venda', tipoOperacao: 'Onerosas' },
  { cfop: '3202', descricao: 'Devolução de venda de mercadoria adquirida ou recebida de terceiros', classe: 'Dev. venda', tipoOperacao: 'Onerosas' },
  { cfop: '3205', descricao: 'Anulação de valor relativo à prestação de serviço de comunicação', classe: 'Anulação', tipoOperacao: 'Onerosas' },
  { cfop: '3206', descricao: 'Anulação de valor relativo à prestação de serviço de transporte', classe: 'Anulação', tipoOperacao: 'Onerosas' },
  { cfop: '3207', descricao: 'Anulação de valor relativo à venda de energia elétrica', classe: 'Anulação', tipoOperacao: 'Onerosas' },
  { cfop: '3211', descricao: 'Devolução de venda de produção do estabelecimento sob o regime de drawback', classe: 'Dev. venda', tipoOperacao: 'Onerosas' },
  { cfop: '3251', descricao: 'Compra de energia elétrica para distribuição ou comercialização', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '3301', descricao: 'Aquisição de serviço de comunicação para execução de serviço da mesma natureza', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '3351', descricao: 'Aquisição de serviço de transporte para execução de serviço da mesma natureza', classe: 'Aquisição de Transporte', tipoOperacao: 'Onerosas' },
  { cfop: '3352', descricao: 'Aquisição de serviço de transporte por estabelecimento industrial', classe: 'Aquisição de Transporte', tipoOperacao: 'Onerosas' },
  { cfop: '3353', descricao: 'Aquisição de serviço de transporte por estabelecimento comercial', classe: 'Aquisição de Transporte', tipoOperacao: 'Onerosas' },
  { cfop: '3354', descricao: 'Aquisição de serviço de transporte por estabelecimento de prestador de serviço de comunicação', classe: 'Aquisição de Transporte', tipoOperacao: 'Onerosas' },
  { cfop: '3355', descricao: 'Aquisição de serviço de transporte por estabelecimento de geradora ou de distribuidora de energia elétrica', classe: 'Aquisição de Transporte', tipoOperacao: 'Onerosas' },
  { cfop: '3356', descricao: 'Aquisição de serviço de transporte por estabelecimento de produtor rural', classe: 'Aquisição de Transporte', tipoOperacao: 'Onerosas' },
  { cfop: '3503', descricao: 'Devolução de mercadoria exportada que tenha sido recebida com fim específico de exportação', classe: 'Dev. remessa', tipoOperacao: 'Não Onerosas' },
  { cfop: '3551', descricao: 'Compra de bem para o ativo imobilizado', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '3553', descricao: 'Devolução de venda de bem do ativo imobilizado', classe: 'Dev. venda', tipoOperacao: 'Onerosas' },
  { cfop: '3556', descricao: 'Compra de material para uso ou consumo', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '3651', descricao: 'Compra de combustível ou lubrificante para industrialização subseqüente', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '3652', descricao: 'Compra de combustível ou lubrificante para comercialização', classe: 'Compra de Combustível', tipoOperacao: 'Onerosas' },
  { cfop: '3653', descricao: 'Compra de combustível ou lubrificante por consumidor ou usuário final', classe: 'Compras', tipoOperacao: 'Onerosas' },
  { cfop: '3930', descricao: 'Lançamento efetuado a título de entrada de bem sob amparo de regime especial aduaneiro de admissão temporária', classe: 'Entrada', tipoOperacao: 'Não Onerosas' },
  { cfop: '3949', descricao: 'Outra entrada de mercadoria ou prestação de serviço não especificado', classe: 'Out. entr/aquis', tipoOperacao: 'Depende - Avaliar cada Cenário SGB' },

  // ── SÉRIE 5000: SAÍDAS ESTADUAIS ──
  { cfop: '5101', descricao: 'Venda de produção do estabelecimento', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '5102', descricao: 'Venda de mercadoria adquirida ou recebida de terceiros', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '5103', descricao: 'Venda de produção do estabelecimento, efetuada fora do estabelecimento', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '5104', descricao: 'Venda de mercadoria adquirida ou recebida de terceiros, efetuada fora do estabelecimento', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '5105', descricao: 'Venda de produção do estabelecimento que não deva por ele transitar', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '5106', descricao: 'Venda de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '5109', descricao: 'Venda de produção do estabelecimento, destinada à Zona Franca de Manaus ou áreas de livre comércio', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '5110', descricao: 'Venda de mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou áreas de livre comércio', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '5111', descricao: 'Venda de produção do estabelecimento remetida anteriormente em consignação industrial', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '5112', descricao: 'Venda de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignação industrial', classe: 'Venda de Combustível', tipoOperacao: 'Onerosas' },
  { cfop: '5113', descricao: 'Venda de produção do estabelecimento remetida anteriormente em consignação mercantil', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '5114', descricao: 'Venda de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignação mercantil', classe: 'Venda de Combustível', tipoOperacao: 'Onerosas' },
  { cfop: '5115', descricao: 'Venda de mercadoria adquirida ou recebida de terceiros, recebida anteriormente em consignação mercantil', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '5116', descricao: 'Venda de produção do estabelecimento originada de encomenda para entrega futura', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '5117', descricao: 'Venda de mercadoria adquirida ou recebida de terceiros, originada de encomenda para entrega futura', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '5118', descricao: 'Venda de produção do estabelecimento entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '5119', descricao: 'Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '5120', descricao: 'Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário pelo vendedor remetente, em venda à ordem', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '5122', descricao: 'Venda de produção do estabelecimento remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '5123', descricao: 'Venda de mercadoria adquirida ou recebida de terceiros remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '5124', descricao: 'Industrialização efetuada para outra empresa', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '5125', descricao: 'Industrialização efetuada para outra empresa quando a mercadoria recebida para utilização no processo de industrialização não transitar pelo estabelecimento adquirente da mercadoria', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '5151', descricao: 'Transferência de produção do estabelecimento', classe: 'Transferência', tipoOperacao: 'Não Onerosas' },
  { cfop: '5152', descricao: 'Transferência de mercadoria adquirida ou recebida de terceiros', classe: 'Transferência', tipoOperacao: 'Não Onerosas' },
  { cfop: '5153', descricao: 'Transferência de energia elétrica', classe: 'Transferência', tipoOperacao: 'Não Onerosas' },
  { cfop: '5155', descricao: 'Transferência de produção do estabelecimento, que não deva por ele transitar', classe: 'Transferência', tipoOperacao: 'Não Onerosas' },
  { cfop: '5156', descricao: 'Transferência de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar', classe: 'Transferência', tipoOperacao: 'Não Onerosas' },
  { cfop: '5201', descricao: 'Devolução de compra para industrialização ou produção rural', classe: 'Dev. compra', tipoOperacao: 'Onerosas' },
  { cfop: '5202', descricao: 'Devolução de compra para comercialização', classe: 'Dev. compra', tipoOperacao: 'Onerosas' },
  { cfop: '5205', descricao: 'Anulação de valor relativo a aquisição de serviço de comunicação', classe: 'Anulação', tipoOperacao: 'Onerosas' },
  { cfop: '5206', descricao: 'Anulação de valor relativo a aquisição de serviço de transporte', classe: 'Anulação', tipoOperacao: 'Onerosas' },
  { cfop: '5207', descricao: 'Anulação de valor relativo à compra de energia elétrica', classe: 'Anulação', tipoOperacao: 'Onerosas' },
  { cfop: '5208', descricao: 'Devolução de mercadoria recebida em transferência para industrialização ou produção rural', classe: 'Transferência', tipoOperacao: 'Não Onerosas' },
  { cfop: '5209', descricao: 'Devolução de mercadoria recebida em transferência para comercialização', classe: 'Transferência', tipoOperacao: 'Não Onerosas' },
  { cfop: '5210', descricao: 'Devolução de compra para utilização na prestação de serviço', classe: 'Dev. compra', tipoOperacao: 'Onerosas' },
  { cfop: '5251', descricao: 'Venda de energia elétrica para distribuição ou comercialização', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '5252', descricao: 'Venda de energia elétrica para estabelecimento industrial', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '5253', descricao: 'Venda de energia elétrica para estabelecimento comercial', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '5254', descricao: 'Venda de energia elétrica para estabelecimento prestador de serviço de transporte', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '5255', descricao: 'Venda de energia elétrica para estabelecimento prestador de serviço de comunicação', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '5256', descricao: 'Venda de energia elétrica para estabelecimento de produtor rural', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '5257', descricao: 'Venda de energia elétrica para consumo por demanda contratada', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '5258', descricao: 'Venda de energia elétrica a não contribuinte', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '5301', descricao: 'Prestação de serviço de comunicação para execução de serviço da mesma natureza', classe: 'Prestação', tipoOperacao: 'Onerosas' },
  { cfop: '5302', descricao: 'Prestação de serviço de comunicação a estabelecimento industrial', classe: 'Prestação', tipoOperacao: 'Onerosas' },
  { cfop: '5303', descricao: 'Prestação de serviço de comunicação a estabelecimento comercial', classe: 'Prestação', tipoOperacao: 'Onerosas' },
  { cfop: '5304', descricao: 'Prestação de serviço de comunicação a estabelecimento de prestador de serviço de transporte', classe: 'Prestação', tipoOperacao: 'Onerosas' },
  { cfop: '5305', descricao: 'Prestação de serviço de comunicação a estabelecimento de geradora ou de distribuidora de energia elétrica', classe: 'Prestação', tipoOperacao: 'Onerosas' },
  { cfop: '5306', descricao: 'Prestação de serviço de comunicação a estabelecimento de produtor rural', classe: 'Prestação', tipoOperacao: 'Onerosas' },
  { cfop: '5307', descricao: 'Prestação de serviço de comunicação a não contribuinte', classe: 'Prestação', tipoOperacao: 'Onerosas' },
  { cfop: '5351', descricao: 'Prestação de serviço de transporte para execução de serviço da mesma natureza', classe: 'Prestação', tipoOperacao: 'Onerosas' },
  { cfop: '5352', descricao: 'Prestação de serviço de transporte a estabelecimento industrial', classe: 'Prestação', tipoOperacao: 'Onerosas' },
  { cfop: '5353', descricao: 'Prestação de serviço de transporte a estabelecimento comercial', classe: 'Prestação', tipoOperacao: 'Onerosas' },
  { cfop: '5354', descricao: 'Prestação de serviço de transporte a estabelecimento de prestador de serviço de comunicação', classe: 'Prestação', tipoOperacao: 'Onerosas' },
  { cfop: '5355', descricao: 'Prestação de serviço de transporte a estabelecimento de geradora ou de distribuidora de energia elétrica', classe: 'Prestação', tipoOperacao: 'Onerosas' },
  { cfop: '5356', descricao: 'Prestação de serviço de transporte a estabelecimento de produtor rural', classe: 'Prestação', tipoOperacao: 'Onerosas' },
  { cfop: '5357', descricao: 'Prestação de serviço de transporte a não contribuinte', classe: 'Prestação', tipoOperacao: 'Onerosas' },
  { cfop: '5359', descricao: 'Prestação de serviço de transporte a contribuinte ou a não contribuinte quando a mercadoria transportada está dispensada de emissão de nota fiscal.', classe: 'Prestação', tipoOperacao: 'Onerosas' },
  { cfop: '5360', descricao: 'Prestação de serviço de transporte a contribuinte substituto em relação ao serviço de transporte', classe: 'Prestação', tipoOperacao: 'Onerosas' },
  { cfop: '5401', descricao: 'Venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária, na condição de contribuinte substituto', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '5402', descricao: 'Venda de produção do estabelecimento de produto sujeito ao regime de substituição tributária, em operação entre contribuintes substitutos do mesmo produto', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '5403', descricao: 'Venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária, na condição de contribuinte substituto', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '5405', descricao: 'Venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária, na condição de contribuinte substituído', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '5408', descricao: 'Transferência de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária', classe: 'Transferência', tipoOperacao: 'Não Onerosas' },
  { cfop: '5409', descricao: 'Transferência de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária', classe: 'Transferência', tipoOperacao: 'Não Onerosas' },
  { cfop: '5410', descricao: 'Devolução de compra para industrialização ou produção rural em operação com mercadoria sujeita ao regime de substituição tributária', classe: 'Dev. compra', tipoOperacao: 'Onerosas' },
  { cfop: '5411', descricao: 'Devolução de compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária', classe: 'Dev. compra', tipoOperacao: 'Onerosas' },
  { cfop: '5412', descricao: 'Devolução de bem do ativo imobilizado, em operação com mercadoria sujeita ao regime de substituição tributária', classe: 'Dev. compra', tipoOperacao: 'Onerosas' },
  { cfop: '5413', descricao: 'Devolução de mercadoria destinada ao uso ou consumo, em operação com mercadoria sujeita ao regime de substituição tributária', classe: 'Dev. compra', tipoOperacao: 'Onerosas' },
  { cfop: '5414', descricao: 'Remessa de produção do estabelecimento para venda fora do estabelecimento em operação com produto sujeito ao regime de substituição tributária', classe: 'Remessa', tipoOperacao: 'Não Onerosas' },
  { cfop: '5415', descricao: 'Remessa de mercadoria adquirida ou recebida de terceiros para venda fora do estabelecimento, em operação com mercadoria sujeita ao regime de substituição tributária', classe: 'Remessa', tipoOperacao: 'Não Onerosas' },
  { cfop: '5451', descricao: 'Remessa de animal e de insumo para estabelecimento produtor', classe: 'Remessa', tipoOperacao: 'Não Onerosas' },
  { cfop: '5501', descricao: 'Remessa de produção do estabelecimento, com fim específico de exportação', classe: 'Remessa', tipoOperacao: 'Não Onerosas' },
  { cfop: '5502', descricao: 'Remessa de mercadoria adquirida ou recebida de terceiros, com fim específico de exportação', classe: 'Remessa', tipoOperacao: 'Não Onerosas' },
  { cfop: '5503', descricao: 'Devolução de mercadoria recebida com fim específico de exportação', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '5504', descricao: 'Remessa de mercadorias para formação de lote de exportação, de produtos industrializados ou produzidos pelo próprio estabelecimento.', classe: 'Remessa', tipoOperacao: 'Não Onerosas' },
  { cfop: '5505', descricao: 'Remessa de mercadorias, adquiridas ou recebidas de terceiros, para formação de lote de exportação', classe: 'Remessa', tipoOperacao: 'Não Onerosas' },
  { cfop: '5551', descricao: 'Venda de bem do ativo imobilizado', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '5552', descricao: 'Transferência de bem do ativo imobilizado', classe: 'Transferência', tipoOperacao: 'Não Onerosas' },
  { cfop: '5553', descricao: 'Devolução de compra de bem para o ativo imobilizado', classe: 'Dev. compra', tipoOperacao: 'Onerosas' },
  { cfop: '5554', descricao: 'Remessa de bem do ativo imobilizado para uso fora do estabelecimento', classe: 'Remessa', tipoOperacao: 'Não Onerosas' },
  { cfop: '5555', descricao: 'Devolução de bem do ativo imobilizado de terceiro, recebido para uso no estabelecimento', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '5556', descricao: 'Devolução de compra de material de uso ou consumo', classe: 'Dev. compra', tipoOperacao: 'Onerosas' },
  { cfop: '5557', descricao: 'Transferência de material de uso ou consumo', classe: 'Transferência', tipoOperacao: 'Não Onerosas' },
  { cfop: '5601', descricao: 'Transferência de crédito de ICMS acumulado', classe: 'Financeira', tipoOperacao: 'Não Onerosas' },
  { cfop: '5602', descricao: 'Transferência de saldo credor de ICMS para outro estabelecimento da mesma empresa, destinado à compensação de saldo devedor de ICMS', classe: 'Financeira', tipoOperacao: 'Não Onerosas' },
  { cfop: '5603', descricao: 'Ressarcimento de ICMS retido por substituição tributária', classe: 'Ressarcimento', tipoOperacao: 'Não Onerosas' },
  { cfop: '5605', descricao: 'Transferência de saldo devedor de ICMS de outro estabelecimento da mesma empresa.', classe: 'Financeira', tipoOperacao: 'Não Onerosas' },
  { cfop: '5606', descricao: 'Utilização de saldo credor de ICMS para extinção por compensação de débitos fiscais.', classe: 'Financeira', tipoOperacao: 'Não Onerosas' },
  { cfop: '5651', descricao: 'Venda de combustível ou lubrificante de produção do estabelecimento destinado à industrialização subseqüente', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '5652', descricao: 'Venda de combustível ou lubrificante de produção do estabelecimento destinado à comercialização', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '5653', descricao: 'Venda de combustível ou lubrificante de produção do estabelecimento destinado a consumidor ou usuário final', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '5654', descricao: 'Venda de combustível ou lubrificante adquirido ou recebido de terceiros destinado à industrialização subseqüente', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '5655', descricao: 'Venda de combustível ou lubrificante adquirido ou recebido de terceiros destinado à comercialização', classe: 'Venda de Combustível', tipoOperacao: 'Onerosas' },
  { cfop: '5656', descricao: 'Venda de combustível ou lubrificante adquirido ou recebido de terceiros destinado a consumidor ou usuário final', classe: 'Venda de Combustível', tipoOperacao: 'Onerosas' },
  { cfop: '5657', descricao: 'Remessa de combustível ou lubrificante adquirido ou recebido de terceiros para venda fora do estabelecimento', classe: 'Remessa', tipoOperacao: 'Não Onerosas' },
  { cfop: '5658', descricao: 'Transferência de combustível ou lubrificante de produção do estabelecimento', classe: 'Transferência', tipoOperacao: 'Não Onerosas' },
  { cfop: '5659', descricao: 'Transferência de combustível ou lubrificante adquirido ou recebido de terceiro', classe: 'Transferência Combustível', tipoOperacao: 'Não Onerosas' },
  { cfop: '5660', descricao: 'Devolução de compra de combustível ou lubrificante adquirido para industrialização subseqüente', classe: 'Dev. compra', tipoOperacao: 'Onerosas' },
  { cfop: '5661', descricao: 'Devolução de compra de combustível ou lubrificante adquirido para comercialização', classe: 'Dev. Compra de Combustível', tipoOperacao: 'Onerosas' },
  { cfop: '5662', descricao: 'Devolução de compra de combustível ou lubrificante adquirido por consumidor ou usuário final', classe: 'Dev. compra', tipoOperacao: 'Onerosas' },
  { cfop: '5663', descricao: 'Remessa para armazenagem de combustível ou lubrificante', classe: 'Remessa', tipoOperacao: 'Não Onerosas' },
  { cfop: '5664', descricao: 'Retorno de combustível ou lubrificante recebido para armazenagem', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '5665', descricao: 'Retorno simbólico de combustível ou lubrificante recebido para armazenagem', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '5666', descricao: 'Remessa por conta e ordem de terceiros de combustível ou lubrificante recebido para armazenagem', classe: 'Remessa', tipoOperacao: 'Não Onerosas' },
  { cfop: '5667', descricao: 'Venda de combustível ou lubrificante a consumidor ou usuário final estabelecido em outra unidade da Federação', classe: 'Venda de Combustível', tipoOperacao: 'Onerosas' },
  { cfop: '5901', descricao: 'Remessa para industrialização por encomenda', classe: 'Remessa', tipoOperacao: 'Não Onerosas' },
  { cfop: '5902', descricao: 'Retorno de mercadoria utilizada na industrialização por encomenda', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '5903', descricao: 'Retorno de mercadoria recebida para industrialização e não aplicada no referido processo', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '5904', descricao: 'Remessa para venda fora do estabelecimento', classe: 'Remessa', tipoOperacao: 'Não Onerosas' },
  { cfop: '5905', descricao: 'Remessa para depósito fechado ou armazém geral', classe: 'Remessa', tipoOperacao: 'Não Onerosas' },
  { cfop: '5906', descricao: 'Retorno de mercadoria depositada em depósito fechado ou armazém geral', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '5907', descricao: 'Retorno simbólico de mercadoria depositada em depósito fechado ou armazém geral', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '5908', descricao: 'Remessa de bem por conta de contrato de comodato', classe: 'Remessa', tipoOperacao: 'Não Onerosas' },
  { cfop: '5909', descricao: 'Retorno de bem recebido por conta de contrato de comodato', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '5910', descricao: 'Remessa em bonificação, doação ou brinde', classe: 'Remessa', tipoOperacao: 'Não Onerosas' },
  { cfop: '5911', descricao: 'Remessa de amostra grátis', classe: 'Remessa', tipoOperacao: 'Não Onerosas' },
  { cfop: '5912', descricao: 'Remessa de mercadoria ou bem para demonstração', classe: 'Remessa', tipoOperacao: 'Não Onerosas' },
  { cfop: '5913', descricao: 'Retorno de mercadoria ou bem recebido para demonstração', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '5914', descricao: 'Remessa de mercadoria ou bem para exposição ou feira', classe: 'Remessa', tipoOperacao: 'Não Onerosas' },
  { cfop: '5915', descricao: 'Remessa de mercadoria ou bem para conserto ou reparo', classe: 'Remessa', tipoOperacao: 'Não Onerosas' },
  { cfop: '5916', descricao: 'Retorno de mercadoria ou bem recebido para conserto ou reparo', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '5917', descricao: 'Remessa de mercadoria em consignação mercantil ou industrial', classe: 'Remessa', tipoOperacao: 'Não Onerosas' },
  { cfop: '5918', descricao: 'Devolução de mercadoria recebida em consignação mercantil ou industrial', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '5919', descricao: 'Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, recebida anteriormente em consignação mercantil ou industrial', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '5920', descricao: 'Remessa de vasilhame ou sacaria', classe: 'Remessa', tipoOperacao: 'Não Onerosas' },
  { cfop: '5921', descricao: 'Devolução de vasilhame ou sacaria', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '5922', descricao: 'Lançamento efetuado a título de simples faturamento decorrente de venda para entrega futura', classe: 'Financeira', tipoOperacao: 'Não Onerosas' },
  { cfop: '5923', descricao: 'Remessa de mercadoria por conta e ordem de terceiros, em venda à ordem ou em operações com armazém geral ou depósito fechado', classe: 'Remessa', tipoOperacao: 'Não Onerosas' },
  { cfop: '5924', descricao: 'Remessa para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente', classe: 'Remessa', tipoOperacao: 'Não Onerosas' },
  { cfop: '5925', descricao: 'Retorno de mercadoria recebida para industrialização por conta e ordem do adquirente da mercadoria, quando aquela não transitar pelo estabelecimento do adquirente', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '5926', descricao: 'Lançamento efetuado a título de reclassificação de mercadoria decorrente de formação de kit ou de sua desagregação', classe: 'Aj. estoque', tipoOperacao: 'Não Onerosas' },
  { cfop: '5927', descricao: 'Lançamento efetuado a título de baixa de estoque decorrente de perda, roubo ou deterioração', classe: 'Aj. estoque', tipoOperacao: 'Não Onerosas' },
  { cfop: '5928', descricao: 'Lançamento efetuado a título de baixa de estoque decorrente do encerramento da atividade da empresa', classe: 'Aj. estoque', tipoOperacao: 'Não Onerosas' },
  { cfop: '5929', descricao: 'Lançamento efetuado em decorrência de emissão de documento fiscal relativo a operação ou prestação também registrada em equipamento Emissor de Cupom Fiscal – ECF', classe: 'Financeira', tipoOperacao: 'Não Onerosas' },
  { cfop: '5931', descricao: 'Lançamento efetuado em decorrência da responsabilidade de retenção do imposto por substituição tributária, atribuída ao remetente ou alienante da mercadoria', classe: 'Financeira', tipoOperacao: 'Não Onerosas' },
  { cfop: '5932', descricao: 'Prestação de serviço de transporte iniciada em unidade da Federação diversa daquela onde inscrito o prestador', classe: 'Prestação', tipoOperacao: 'Onerosas' },
  { cfop: '5933', descricao: 'Prestação de serviço tributado pelo ISS', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '5934', descricao: 'Remessa simbólica de mercadoria depositada em armazém geral ou depósito fechado', classe: 'Remessa', tipoOperacao: 'Não Onerosas' },
  { cfop: '5949', descricao: 'Outra saída de mercadoria ou prestação de serviço não especificado', classe: 'Out. saída/prest', tipoOperacao: 'Depende - Avaliar cada Cenário SGB' },

  // ── SÉRIE 6000: SAÍDAS INTERESTADUAIS ──
  { cfop: '6101', descricao: 'Venda de produção do estabelecimento', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '6102', descricao: 'Venda de mercadoria adquirida ou recebida de terceiros', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '6103', descricao: 'Venda de produção do estabelecimento, efetuada fora do estabelecimento', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '6104', descricao: 'Venda de mercadoria adquirida ou recebida de terceiros, efetuada fora do estabelecimento', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '6105', descricao: 'Venda de produção do estabelecimento que não deva por ele transitar', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '6106', descricao: 'Venda de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '6107', descricao: 'Venda de produção do estabelecimento, destinada a não contribuinte', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '6108', descricao: 'Venda de mercadoria adquirida ou recebida de terceiros, destinada a não contribuinte', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '6109', descricao: 'Venda de produção do estabelecimento, destinada à Zona Franca de Manaus ou áreas de livre comércio', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '6110', descricao: 'Venda de mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou áreas de livre comércio', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '6111', descricao: 'Venda de produção do estabelecimento remetida anteriormente em consignação industrial', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '6112', descricao: 'Venda de mercadoria adquirida ou recebida de Terceiros remetida anteriormente em consignação industrial', classe: 'Venda de Combustível', tipoOperacao: 'Onerosas' },
  { cfop: '6113', descricao: 'Venda de produção do estabelecimento remetida anteriormente em consignação mercantil', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '6114', descricao: 'Venda de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignação mercantil', classe: 'Venda de Combustível', tipoOperacao: 'Onerosas' },
  { cfop: '6115', descricao: 'Venda de mercadoria adquirida ou recebida de terceiros, recebida anteriormente em consignação mercantil', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '6116', descricao: 'Venda de produção do estabelecimento originada de encomenda para entrega futura', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '6117', descricao: 'Venda de mercadoria adquirida ou recebida de terceiros, originada de encomenda para entrega futura', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '6118', descricao: 'Venda de produção do estabelecimento entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '6119', descricao: 'Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '6120', descricao: 'Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário pelo vendedor remetente, em venda à ordem', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '6122', descricao: 'Venda de produção do estabelecimento remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '6123', descricao: 'Venda de mercadoria adquirida ou recebida de terceiros remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '6124', descricao: 'Industrialização efetuada para outra empresa', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '6125', descricao: 'Industrialização efetuada para outra empresa quando a mercadoria recebida para utilização no processo de industrialização não transitar pelo estabelecimento adquirente da mercadoria', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '6151', descricao: 'Transferência de produção do estabelecimento', classe: 'Transferência', tipoOperacao: 'Não Onerosas' },
  { cfop: '6152', descricao: 'Transferência de mercadoria adquirida ou recebida de terceiros', classe: 'Transferência', tipoOperacao: 'Não Onerosas' },
  { cfop: '6153', descricao: 'Transferência de energia elétrica', classe: 'Transferência', tipoOperacao: 'Não Onerosas' },
  { cfop: '6155', descricao: 'Transferência de produção do estabelecimento, que não deva por ele transitar', classe: 'Transferência', tipoOperacao: 'Não Onerosas' },
  { cfop: '6156', descricao: 'Transferência de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar', classe: 'Transferência', tipoOperacao: 'Não Onerosas' },
  { cfop: '6201', descricao: 'Devolução de compra para industrialização ou produção rural', classe: 'Dev. compra', tipoOperacao: 'Onerosas' },
  { cfop: '6202', descricao: 'Devolução de compra para comercialização', classe: 'Dev. compra', tipoOperacao: 'Onerosas' },
  { cfop: '6205', descricao: 'Anulação de valor relativo a aquisição de serviço de comunicação', classe: 'Anulação', tipoOperacao: 'Onerosas' },
  { cfop: '6206', descricao: 'Anulação de valor relativo a aquisição de serviço de transporte', classe: 'Anulação', tipoOperacao: 'Onerosas' },
  { cfop: '6207', descricao: 'Anulação de valor relativo à compra de energia elétrica', classe: 'Anulação', tipoOperacao: 'Onerosas' },
  { cfop: '6208', descricao: 'Devolução de mercadoria recebida em transferência para industrialização ou produção rural', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '6209', descricao: 'Devolução de mercadoria recebida em transferência para comercialização', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '6210', descricao: 'Devolução de compra para utilização na prestação de serviço', classe: 'Dev. compra', tipoOperacao: 'Onerosas' },
  { cfop: '6251', descricao: 'Venda de energia elétrica para distribuição ou comercialização', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '6252', descricao: 'Venda de energia elétrica para estabelecimento industrial', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '6253', descricao: 'Venda de energia elétrica para estabelecimento comercial', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '6254', descricao: 'Venda de energia elétrica para estabelecimento prestador de serviço de transporte', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '6255', descricao: 'Venda de energia elétrica para estabelecimento prestador de serviço de comunicação', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '6256', descricao: 'Venda de energia elétrica para estabelecimento de produtor rural', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '6257', descricao: 'Venda de energia elétrica para consumo por demanda contratada', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '6258', descricao: 'Venda de energia elétrica a não contribuinte', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '6301', descricao: 'Prestação de serviço de comunicação para execução de serviço da mesma natureza', classe: 'Prestação', tipoOperacao: 'Onerosas' },
  { cfop: '6302', descricao: 'Prestação de serviço de comunicação a estabelecimento industrial', classe: 'Prestação', tipoOperacao: 'Onerosas' },
  { cfop: '6303', descricao: 'Prestação de serviço de comunicação a estabelecimento comercial', classe: 'Prestação', tipoOperacao: 'Onerosas' },
  { cfop: '6304', descricao: 'Prestação de serviço de comunicação a estabelecimento de prestador de serviço de transporte', classe: 'Prestação', tipoOperacao: 'Onerosas' },
  { cfop: '6305', descricao: 'Prestação de serviço de comunicação a estabelecimento de geradora ou de distribuidora de energia elétrica', classe: 'Prestação', tipoOperacao: 'Onerosas' },
  { cfop: '6306', descricao: 'Prestação de serviço de comunicação a estabelecimento de produtor rural', classe: 'Prestação', tipoOperacao: 'Onerosas' },
  { cfop: '6307', descricao: 'Prestação de serviço de comunicação a não contribuinte', classe: 'Prestação', tipoOperacao: 'Onerosas' },
  { cfop: '6351', descricao: 'Prestação de serviço de transporte para execução de serviço da mesma natureza', classe: 'Prestação', tipoOperacao: 'Onerosas' },
  { cfop: '6352', descricao: 'Prestação de serviço de transporte a estabelecimento industrial', classe: 'Prestação', tipoOperacao: 'Onerosas' },
  { cfop: '6353', descricao: 'Prestação de serviço de transporte a estabelecimento comercial', classe: 'Prestação', tipoOperacao: 'Onerosas' },
  { cfop: '6354', descricao: 'Prestação de serviço de transporte a estabelecimento de prestador de serviço de comunicação', classe: 'Prestação', tipoOperacao: 'Onerosas' },
  { cfop: '6355', descricao: 'Prestação de serviço de transporte a estabelecimento de geradora ou de distribuidora de energia elétrica', classe: 'Prestação', tipoOperacao: 'Onerosas' },
  { cfop: '6356', descricao: 'Prestação de serviço de transporte a estabelecimento de produtor rural', classe: 'Prestação', tipoOperacao: 'Onerosas' },
  { cfop: '6357', descricao: 'Prestação de serviço de transporte a não contribuinte', classe: 'Prestação', tipoOperacao: 'Onerosas' },
  { cfop: '6359', descricao: 'Prestação de serviço de transporte a contribuinte ou a não contribuinte quando a mercadoria transportada está dispensada de emissão de nota fiscal.', classe: 'Prestação', tipoOperacao: 'Onerosas' },
  { cfop: '6360', descricao: 'Prestação de serviço de transporte a contribuinte substituto em relação ao serviço de transporte.', classe: 'Prestação', tipoOperacao: 'Onerosas' },
  { cfop: '6401', descricao: 'Venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária, na condição de contribuinte substituto', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '6402', descricao: 'Venda de produção do estabelecimento de produto sujeito ao regime de substituição tributária, em operação entre contribuintes substitutos do mesmo produto', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '6403', descricao: 'Venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária, na condição de contribuinte substituto', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '6404', descricao: 'Venda de mercadoria sujeita ao regime de substituição tributária, cujo imposto já tenha sido retido anteriormente', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '6408', descricao: 'Transferência de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária', classe: 'Transferência', tipoOperacao: 'Não Onerosas' },
  { cfop: '6409', descricao: 'Transferência de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária', classe: 'Transferência', tipoOperacao: 'Não Onerosas' },
  { cfop: '6410', descricao: 'Devolução de compra para industrialização ou produção rural em operação com mercadoria sujeita ao regime de substituição tributária', classe: 'Dev. compra', tipoOperacao: 'Onerosas' },
  { cfop: '6411', descricao: 'Devolução de compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária', classe: 'Dev. compra', tipoOperacao: 'Onerosas' },
  { cfop: '6412', descricao: 'Devolução de bem do ativo imobilizado, em operação com mercadoria sujeita ao regime de substituição tributária', classe: 'Dev. compra', tipoOperacao: 'Onerosas' },
  { cfop: '6413', descricao: 'Devolução de mercadoria destinada ao uso ou consumo, em operação com mercadoria sujeita ao regime de substituição tributária', classe: 'Dev. compra', tipoOperacao: 'Onerosas' },
  { cfop: '6414', descricao: 'Remessa de produção do estabelecimento para venda fora do estabelecimento em operação com produto sujeito ao regime de substituição tributária', classe: 'Remessa', tipoOperacao: 'Não Onerosas' },
  { cfop: '6415', descricao: 'Remessa de mercadoria adquirida ou recebida de terceiros para venda fora do estabelecimento, em operação com mercadoria sujeita ao regime de substituição tributária', classe: 'Remessa', tipoOperacao: 'Não Onerosas' },
  { cfop: '6501', descricao: 'Remessa de produção do estabelecimento, com fim específico de exportação', classe: 'Remessa', tipoOperacao: 'Não Onerosas' },
  { cfop: '6502', descricao: 'Remessa de mercadoria adquirida ou recebida de terceiros, com fim específico de exportação', classe: 'Remessa', tipoOperacao: 'Não Onerosas' },
  { cfop: '6503', descricao: 'Devolução de mercadoria recebida com fim específico de exportação', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '6504', descricao: 'Remessa de mercadorias para formação de lote de exportação, de produtos industrializados ou produzidos pelo próprio estabelecimento.', classe: 'Remessa', tipoOperacao: 'Não Onerosas' },
  { cfop: '6505', descricao: 'Remessa de mercadorias, adquiridas ou recebidas de terceiros, para formação de lote de exportação', classe: 'Remessa', tipoOperacao: 'Não Onerosas' },
  { cfop: '6551', descricao: 'Venda de bem do ativo imobilizado', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '6552', descricao: 'Transferência de bem do ativo imobilizado', classe: 'Transferência', tipoOperacao: 'Não Onerosas' },
  { cfop: '6553', descricao: 'Devolução de compra de bem para o ativo imobilizado', classe: 'Dev. compra', tipoOperacao: 'Onerosas' },
  { cfop: '6554', descricao: 'Remessa de bem do ativo imobilizado para uso fora do estabelecimento', classe: 'Remessa', tipoOperacao: 'Não Onerosas' },
  { cfop: '6555', descricao: 'Devolução de bem do ativo imobilizado de terceiro, recebido para uso no estabelecimento', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '6556', descricao: 'Devolução de compra de material de uso ou consumo', classe: 'Dev. compra', tipoOperacao: 'Onerosas' },
  { cfop: '6557', descricao: 'Transferência de material de uso ou consumo', classe: 'Transferência', tipoOperacao: 'Não Onerosas' },
  { cfop: '6603', descricao: 'Ressarcimento de ICMS retido por substituição tributária', classe: 'Ressarcimento', tipoOperacao: 'Não Onerosas' },
  { cfop: '6651', descricao: 'Venda de combustível ou lubrificante de produção do estabelecimento destinado à industrialização subseqüente', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '6652', descricao: 'Venda de combustível ou lubrificante de produção do estabelecimento destinado à comercialização', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '6653', descricao: 'Venda de combustível ou lubrificante de produção do estabelecimento destinado a consumidor ou usuário final', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '6654', descricao: 'Venda de combustível ou lubrificante adquirido ou recebido de terceiros destinado à industrialização subseqüente', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '6655', descricao: 'Venda de combustível ou lubrificante adquirido ou recebido de terceiros destinado à comercialização', classe: 'Venda de Combustível', tipoOperacao: 'Onerosas' },
  { cfop: '6656', descricao: 'Venda de combustível ou lubrificante adquirido ou recebido de terceiros destinado a consumidor ou usuário final', classe: 'Venda de Combustível', tipoOperacao: 'Onerosas' },
  { cfop: '6657', descricao: 'Remessa de combustível ou lubrificante adquirido ou recebido de terceiros para venda fora do estabelecimento', classe: 'Remessa', tipoOperacao: 'Não Onerosas' },
  { cfop: '6658', descricao: 'Transferência de combustível ou lubrificante de produção do estabelecimento', classe: 'Transferência', tipoOperacao: 'Não Onerosas' },
  { cfop: '6659', descricao: 'Transferência de combustível ou lubrificante adquirido ou recebido de terceiro', classe: 'Transferência Combustível', tipoOperacao: 'Não Onerosas' },
  { cfop: '6660', descricao: 'Devolução de compra de combustível ou lubrificante adquirido para industrialização subseqüente', classe: 'Dev. compra', tipoOperacao: 'Onerosas' },
  { cfop: '6661', descricao: 'Devolução de compra de combustível ou lubrificante adquirido para comercialização', classe: 'Dev. Compra de Combustível', tipoOperacao: 'Onerosas' },
  { cfop: '6662', descricao: 'Devolução de compra de combustível ou lubrificante adquirido por consumidor ou usuário final', classe: 'Dev. compra', tipoOperacao: 'Onerosas' },
  { cfop: '6663', descricao: 'Remessa para armazenagem de combustível ou lubrificante', classe: 'Remessa', tipoOperacao: 'Não Onerosas' },
  { cfop: '6664', descricao: 'Retorno de combustível ou lubrificante recebido para armazenagem', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '6665', descricao: 'Retorno simbólico de combustível ou lubrificante recebido para armazenagem', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '6666', descricao: 'Remessa por conta e ordem de terceiros de combustível ou lubrificante recebido para armazenagem', classe: 'Remessa', tipoOperacao: 'Não Onerosas' },
  { cfop: '6667', descricao: 'Venda de combustível ou lubrificante a consumidor ou usuário final estabelecido em outra unidade da Federação diferente da que ocorrer o consumo', classe: 'Venda de Combustível', tipoOperacao: 'Onerosas' },
  { cfop: '6901', descricao: 'Remessa para industrialização por encomenda', classe: 'Remessa', tipoOperacao: 'Não Onerosas' },
  { cfop: '6902', descricao: 'Retorno de mercadoria utilizada na industrialização por encomenda', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '6903', descricao: 'Retorno de mercadoria recebida para industrialização e não aplicada no referido processo', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '6904', descricao: 'Remessa para venda fora do estabelecimento', classe: 'Remessa', tipoOperacao: 'Não Onerosas' },
  { cfop: '6905', descricao: 'Remessa para depósito fechado ou armazém geral', classe: 'Remessa', tipoOperacao: 'Não Onerosas' },
  { cfop: '6906', descricao: 'Retorno de mercadoria depositada em depósito fechado ou armazém geral', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '6907', descricao: 'Retorno simbólico de mercadoria depositada em depósito fechado ou armazém geral', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '6908', descricao: 'Remessa de bem por conta de contrato de comodato', classe: 'Remessa', tipoOperacao: 'Não Onerosas' },
  { cfop: '6909', descricao: 'Retorno de bem recebido por conta de contrato de comodato', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '6910', descricao: 'Remessa em bonificação, doação ou brinde', classe: 'Remessa', tipoOperacao: 'Não Onerosas' },
  { cfop: '6911', descricao: 'Remessa de amostra grátis', classe: 'Remessa', tipoOperacao: 'Não Onerosas' },
  { cfop: '6912', descricao: 'Remessa de mercadoria ou bem para demonstração', classe: 'Remessa', tipoOperacao: 'Não Onerosas' },
  { cfop: '6913', descricao: 'Retorno de mercadoria ou bem recebido para demonstração', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '6914', descricao: 'Remessa de mercadoria ou bem para exposição ou feira', classe: 'Remessa', tipoOperacao: 'Não Onerosas' },
  { cfop: '6915', descricao: 'Remessa de mercadoria ou bem para conserto ou reparo', classe: 'Remessa', tipoOperacao: 'Não Onerosas' },
  { cfop: '6916', descricao: 'Retorno de mercadoria ou bem recebido para conserto ou reparo', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '6917', descricao: 'Remessa de mercadoria em consignação mercantil ou industrial', classe: 'Remessa', tipoOperacao: 'Não Onerosas' },
  { cfop: '6918', descricao: 'Devolução de mercadoria recebida em consignação mercantil ou industrial', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '6919', descricao: 'Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, recebida anteriormente em consignação mercantil ou industrial', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '6920', descricao: 'Remessa de vasilhame ou sacaria', classe: 'Remessa', tipoOperacao: 'Não Onerosas' },
  { cfop: '6921', descricao: 'Devolução de vasilhame ou sacaria', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '6922', descricao: 'Lançamento efetuado a título de simples faturamento decorrente de venda para entrega futura', classe: 'Financeira', tipoOperacao: 'Não Onerosas' },
  { cfop: '6923', descricao: 'Remessa de mercadoria por conta e ordem de terceiros, em venda à ordem ou em operações com armazém geral ou depósito fechado', classe: 'Remessa', tipoOperacao: 'Não Onerosas' },
  { cfop: '6924', descricao: 'Remessa para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente', classe: 'Remessa', tipoOperacao: 'Não Onerosas' },
  { cfop: '6925', descricao: 'Retorno de mercadoria recebida para industrialização por conta e ordem do adquirente da mercadoria, quando aquela não transitar pelo estabelecimento do adquirente', classe: 'Retorno', tipoOperacao: 'Não Onerosas' },
  { cfop: '6929', descricao: 'Lançamento efetuado em decorrência de emissão de documento fiscal relativo a operação ou prestação também registrada em equipamento Emissor de Cupom Fiscal–ECF', classe: 'Financeira', tipoOperacao: 'Não Onerosas' },
  { cfop: '6931', descricao: 'Lançamento efetuado em decorrência da responsabilidade de retenção do imposto por substituição tributária, atribuída ao remetente ou alienante da mercadoria', classe: 'Financeira', tipoOperacao: 'Não Onerosas' },
  { cfop: '6932', descricao: 'Prestação de serviço de transporte iniciada em unidade da Federação diversa daquela onde inscrito o prestador', classe: 'Prestação', tipoOperacao: 'Onerosas' },
  { cfop: '6933', descricao: 'Prestação de serviço tributado pelo ISS', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '6934', descricao: 'Remessa simbólica de mercadoria depositada em armazém geral ou depósito fechado', classe: 'Remessa', tipoOperacao: 'Não Onerosas' },
  { cfop: '6949', descricao: 'Outra saída de mercadoria ou prestação de serviço não especificado', classe: 'Out. saída/prest', tipoOperacao: 'Depende - Avaliar cada Cenário SGB' },

  // ── SÉRIE 7000: SAÍDAS PARA O EXTERIOR ──
  { cfop: '7101', descricao: 'Venda de produção do estabelecimento', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '7102', descricao: 'Venda de mercadoria adquirida ou recebida de terceiros', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '7105', descricao: 'Venda de produção do estabelecimento, que não deva por ele transitar', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '7106', descricao: 'Venda de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '7127', descricao: 'Venda de produção do estabelecimento sob o regime de drawback', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '7201', descricao: 'Devolução de compra para industrialização ou produção rural', classe: 'Dev. compra', tipoOperacao: 'Onerosas' },
  { cfop: '7202', descricao: 'Devolução de compra para comercialização', classe: 'Dev. compra', tipoOperacao: 'Onerosas' },
  { cfop: '7205', descricao: 'Anulação de valor relativo à aquisição de serviço de comunicação', classe: 'Anulação', tipoOperacao: 'Onerosas' },
  { cfop: '7206', descricao: 'Anulação de valor relativo a aquisição de serviço de transporte', classe: 'Anulação', tipoOperacao: 'Onerosas' },
  { cfop: '7207', descricao: 'Anulação de valor relativo à compra de energia elétrica', classe: 'Anulação', tipoOperacao: 'Onerosas' },
  { cfop: '7210', descricao: 'Devolução de compra para utilização na prestação de serviço', classe: 'Dev. compra', tipoOperacao: 'Onerosas' },
  { cfop: '7211', descricao: 'Devolução de compras para industrialização sob o regime de drawback', classe: 'Dev. compra', tipoOperacao: 'Onerosas' },
  { cfop: '7251', descricao: 'Venda de energia elétrica para o exterior', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '7301', descricao: 'Prestação de serviço de comunicação para execução de serviço da mesma natureza', classe: 'Prestação', tipoOperacao: 'Onerosas' },
  { cfop: '7358', descricao: 'Prestação de serviço de transporte', classe: 'Prestação', tipoOperacao: 'Onerosas' },
  { cfop: '7501', descricao: 'Exportação de mercadorias recebidas com fim específico de exportação', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '7551', descricao: 'Venda de bem do ativo imobilizado', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '7553', descricao: 'Devolução de compra de bem para o ativo imobilizado', classe: 'Dev. compra', tipoOperacao: 'Onerosas' },
  { cfop: '7556', descricao: 'Devolução de compra de material de uso ou consumo', classe: 'Dev. compra', tipoOperacao: 'Onerosas' },
  { cfop: '7651', descricao: 'Venda de combustível ou lubrificante de produção do estabelecimento', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '7654', descricao: 'Venda de combustível ou lubrificante adquirido ou recebido de terceiros', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '7667', descricao: 'Venda de combustível ou lubrificante a consumidor ou usuário final.', classe: 'Venda', tipoOperacao: 'Onerosas' },
  { cfop: '7930', descricao: 'Lançamento efetuado a título de devolução de bem cuja entrada tenha ocorrido sob amparo de regime especial aduaneiro de admissão temporária', classe: 'Dev. compra', tipoOperacao: 'Onerosas' },
  { cfop: '7949', descricao: 'Outra saída de mercadoria ou prestação de serviço não especificado', classe: 'Out. saída/prest', tipoOperacao: 'Depende - Avaliar cada Cenário SGB' }
];
